name: Release and Deploy

on:
  push:
    branches: [ "master" ]
    paths:
      - lib/sb/test/version.rb

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: release

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.7
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: 2.7.7
    - name: Build
      run: |
        bundler install
        rake clobber
        rake build
    - name: Get Version
      run: |
        echo "GEM_VERSION=$(bundler exec ruby -e 'require "sb/test/version"; print Sb::Test::VERSION')" | tee -a $GITHUB_ENV
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.GEM_VERSION }}
        release_name: Release ${{ env.GEM_VERSION }}
        body: |
          [Changelog](${{ github.server_url }}/${{ github.repository }}/blob/${{ env.GEM_VERSION }}/CHANGELOG.md)
        draft: false
        prerelease: false
    - name: Deploy
      env:
        RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem push pkg/dragnet-*.gem
